<a href="https://colab.research.google.com/github/HARRY-hussein/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("StudentsPerformance.csv")

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print("First 5 rows of the dataset:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types and null info:")
print(df.info())

Dataset shape (rows, columns): (1000, 8)
Column name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows of the dataset:
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
Summary statistics:
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000
Data types and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [8]:
print("Average scores by subject:")
df[["math score", "reading score", "writing score"]].mean()

Average scores by subject:

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [9]:
print("Maximum scores by subject:")
df[["math score", "reading score", "writing score"]].max()

Maximum scores by subject:

math score       100
reading score    100
writing score    100
dtype: int64

In [10]:
print("Minimum scores by subject:")
df[["math score", "reading score", "writing score"]].min()

Minimum scores by subject:

math score        0
reading score    17
writing score    10
dtype: int64

In [11]:
# Correlation
print("Correlation:")
df[["math score", "reading score", "writing score"]].corr()

Correlation:

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [12]:
# New columns creation
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("New columns preview (total, average, passed):")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes

In [13]:
test_prep_group = df.groupby('test preparation course')[["math score", "reading score", "writing score"]].mean()
print("student score by test preperation course:")
print(test_prep_group)

# Gender-based average
gender_avg = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
print("Average score by gender:")
print(gender_avg)

# Who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:\n", pass_rate)

student score by test preperation course:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
Average score by gender:
        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
Pass rate:
 passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64

In [14]:
# 'math score', 'reading score' va 'writing score' ustunlarini tanlab,
# ularni Numpy massiviga (array) aylantirib oldik
scores = df[["math score", "reading score", "writing score"]].values

# # Mean (o'rtacha qiymat) va Std Deviation (standart chetlanish)
# Har bir ustun (axis=0) bo'yicha o'rtacha qiymatni hisoblaymiz
print("Numpy Mean:", np.mean(scores, axis=0))
# Har bir ustun bo'yicha standart chetlanishni hisoblaymiz
print("Numpy Std:", np.std(scores, axis=0))

# # Z-score (normallashtirish)
# Z-score formulasi: (qiymat - o'rtacha) / standart chetlanish
# Bu ma'lumotlarni o'lchov birliklaridan xalos etib, taqqoslashni osonlashtiradi
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)

print("Z-scores (normalized numbers)")
# Normallashtirilgan ma'lumotlarning dastlabki 5 tasini chiqaramiz
print(z_score[:5])

# Izohlar:
# Average 0  -> Normallashtirilgandan so'ng, o'rtacha qiymat 0 ga teng bo'ladi
# Negative - -> O'rtacha qiymatdan past bo'lgan natijalar
# Positive + -> O'rtacha qiymatdan yuqori bo'lgan natijalar

Numpy Mean: [66.089 69.169 68.054]
Numpy Std: [15.15549666 14.59289002 15.18805728]
Z-scores (normalized numbers)
[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]

In [15]:
# O'rtacha bali 90 va undan yuqori bo'lgan talabalar
# 'average score' ustunidan 90 dan katta yoki teng bo'lgan qatorlarni filtrlash
top_scorers = df[df["average score"] >= 90]
# top_scorers massividagi elementlar sonini (len) hisoblab chiqaramiz
print("Top scored student above 90:", len(top_scorers))

# Imtihondan o'ta olmaganlar sonini aniqlash
# 'passed' ustunida "No" (o'ta olmagan) bo'lgan qatorlarni filtrlash
failed = df[df["passed"] == "No"]
# failed massividagi elementlar sonini (len) hisoblab chiqaramiz
print("Failed from exam:", len(failed))

Top scored student above 90: 52
Failed from exam: 103

In [22]:
# 'passed' ustuni bo'yicha guruhlab, fanlardan average ballarni hisoblash
comparison = df.groupby("passed")[["math score", "reading score", "writing score"]].mean()

print("Average scores of both passed and failed students by subject:")
print(comparison)

Average scores of both passed and failed students by subject:
        math score  reading score  writing score
passed
No       41.514563      43.563107      41.126214
Yes      68.910814      72.109253      71.146042

In [17]:
# "passed" ustunidagi barcha qiymatlar
print("All ranking:")
print(df["passed"].value_counts(dropna=False))

Barcha toifalar taqsimoti:
passed
Yes    897
No     103
Name: count, dtype: int64

In [19]:
# Faqat yiqilganlar guruhi
failed_students = df[df["passed"] == "No"]

# Average scores of failed students by subject
print("Average scores of failed students by subject:")
print(failed_students[["math score", "reading score", "writing score"]].mean())

Yiqilgan talabalarning fanlar kesimida o'rtacha ballari:
math score       41.514563
reading score    43.563107
writing score    41.126214
dtype: float64

In [23]:
# 1. Dividing students into three ranking
# above 80 - "Excellent", 50-80 - "Average", below 50 - "Weak"
def categorize_student(score):
    if score >= 80:
        return 'Excellent'
    elif score >= 50:
        return 'Average'
    else:
        return 'Weak'

# apply() funksiyasi orqali har bir qatorga funksiya qo'llanadi
df['performance_category'] = df['average score'].apply(categorize_student)

# 2. Har bir guruhda nechta talaba bor
category_counts = df['performance_category'].value_counts()
print("Distribution of students by performance level:")
print(category_counts)

# 3. Har bir guruhning matematikadan o'rtacha bali (Taqqoslash uchun)
performance_group_mean = df.groupby('performance_category')[['math score']].mean()
print("\nAverage math score for each performance group:")
print(performance_group_mean)

Talabalarning ishlash darajasi bo'yicha taqsimoti:
performance_category
Average      699
Excellent    198
Weak         103
Name: count, dtype: int64

Average score of each group from math:
                      math score
performance_category
Average                64.314735
Excellent              85.136364
Weak                   41.514563

In [25]:
# "Lunch" va "Test preparation course" holatidagi o‘rtacha ballar
pivot_analysis = df.pivot_table(
    index='lunch',
    columns='test preparation course',
    values='average score',
    aggfunc='mean'
)

print("Impact of lunch and test preparation course on average scores:")
print(pivot_analysis)

# 2. Xulosa chiqarish uchun farq
# Kursga borgan va bormaganlar o'rtasidagi farq
diff = pivot_analysis['completed'] - pivot_analysis['none']
print("\nAverage score difference between students who completed the course and those who did not (in points):")
print(diff)

Impact of lunch and test preparation course on average scores:
test preparation course  completed       none
lunch
free/reduced             67.755725  58.949405
standard                 75.505140  68.302233

Average score difference between students who completed the course and those who did not (in points):
lunch
free/reduced    8.806320
standard        7.202907
dtype: float64